
# Makefile for make a static library

CC=g++
LD=g++
CXX_OBJ=$(patsubst %.cpp,%.o,$(wildcard *.cpp))
SOURCES=$(shell find . -name "*.o")
LIB=target.a

CXXFLAGS=-I .
LDFLAGS=$(LD_OS_DEP)
ARFLAGS=rcs


all: $(CXX_OBJ) $(LIB)

build: clean all

clean:
	-rm *.o *.a $(BIN) *~

.cpp.o:
	@echo "CC " $<
	@$(CC) $(CXXFLAGS) -c $<

$(LIB): *.o
	@echo "AR " $(LIB)
	@$(AR) $(ARFLAGS) $(LIB) $(CXX_OBJ)
