#
# Makefile for static library
#

CXX = g++
LD = g++
CXX_OBJ = $(patsubst %.cpp,%.o,$(wildcard *.cpp))
LIB = libxxx.a

CXXFLAGS = -DVERSION=\"$(VERSION)\"
CXXFLAGS += -I./ -I../ -I../../ -I../../lib/
CXXFLAGS += -Wall -Wno-unused -std=c++14 -g

LDFLAGS=$(LD_OS_DEP)
ARFLAGS=rcs

DEPS := $(CXX_OBJ:.o=.d)
-include $(DEPS)
CXXFLAGS += -MMD -MP

.PHONY: all build clean

all: $(CXX_OBJ) $(LIB)

build: clean all

clean:
	rm -rf $(LIB) $(DEPS) $(CXX_OBJ) *~

.cpp.o:
	@echo "CXX" $<
	@$(CXX) $(CXXFLAGS) -c $<

$(LIB): *.o
	@echo "AR " $(LIB)
	@$(AR) $(ARFLAGS) $(LIB) $(CXX_OBJ)

